### ISSUE TITLE
check_url

### ISSUE THREAD

**Issue by Freshman1001** [Ark4izZ/scripts#1]
`self.check_url = "http://zhjw.scu.edu.cn/j_spring_security_check"`
这个现在不行了，提示token验证失败，请问大佬这个check_url要怎么更改呢？
@Ark4izZ

**Comment by Ark4izZ** [comment]
上次教务系统更新之后就是失效了，我当时重写了一个忘记传了，现在传上来你看看还能不能用

**Comment by Freshman1001** [comment]
好的，谢谢

**Comment by Freshman1001** [comment]
亲测可用，不过学长上传的v2版本没有删除个人信息，大佬可以删一下。

**Comment by Ark4izZ** [comment]
@Freshman1001 哈哈哈尴尬
