### ISSUE TITLE
请问自动打码是不是不能用了

### ISSUE THREAD

**Issue by Moyuren00** [Ark4izZ/scripts#3]
登录的时候一直显示验证码错误

**Comment by Moyuren00** [comment]
不好意思 刚刚不知道为什么失败了 现在又可以了 请忽略验证码这条，但是使用时出现AttributeError: 'QK' object has no attribute 'config_into'该怎么解决

**Comment by Ark4izZ** [comment]
> 不好意思 刚刚不知道为什么失败了 现在又可以了 请忽略验证码这条，但是使用时出现AttributeError: 'QK' object has no attribute 'config_into'该怎么解决

169行改的时候没改完，应该是config_info
